action_bias_only: false
action_noise: 1
action_angle_noise: 0.2
action_step_mean: 1.0
action_step_std: 0.4
action_lower_bd: 0.2
action_upper_bd: 1.8
action_param_xy: true
batch_size: 1024
device: cpu
dot_std: 1.3
border_wall_loc: 5
fix_wall_batch_k: null
fix_wall: true
fix_door_location: 10
fix_wall_location: 32
exclude_wall_train: ''
exclude_door_train: ''
only_wall_val: ''
only_door_val: ''
wall_padding: 20
door_padding: 10
wall_width: 3
door_space: 4
num_train_layouts: -1
cross_wall_rate: 0.60
expert_cross_wall_rate: 0
img_size: 65
max_step: 1
n_steps: 17
n_steps_reduce_factor: 1
noise: 0
normalize: false
size: 20000
val_size: 10000
static_noise: 0
static_noise_speed: 0
train: true
zero_action: false
repeat_actions: 1
normalizer_hardset: false
